language: node_js
sudo: false
services:
  - mongodb
node_js:
  - '5'
  - '4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
- 'npm install -g npm@latest'
notifications:
  email: false
