export const SOUNDCLOUD_LOGIN = 'SOUNDCLOUD_LOGIN';
export const SOUNDCLOUD_FETCH_SUCCESS = 'SOUNDCLOUD_FETCH_SUCCESS';
export const SOUNDCLOUD_NEXTPAGE = 'SOUNDCLOUD_NEXTPAGE';
export const SOUNDCLOUD_PREVPAGE = 'SOUNDCLOUD_PREVPAGE';
export const SOUNDCLOUD_FETCH_MORE_SUCCESS = 'SOUNDCLOUD_FETCH_MORE_SUCCESS';
